// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Scored.proto

package com.kerpow.games.freethrow.common.message.messages;

public final class ScoredOuterClass {
  private ScoredOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ScoredOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.kerpow.games.freethrow.common.Scored)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required int32 score = 2;</code>
     */
    boolean hasScore();
    /**
     * <code>required int32 score = 2;</code>
     */
    int getScore();
  }
  /**
   * Protobuf type {@code com.kerpow.games.freethrow.common.Scored}
   */
  public static final class Scored extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.kerpow.games.freethrow.common.Scored)
      ScoredOrBuilder {
    // Use Scored.newBuilder() to construct.
    private Scored(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Scored(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Scored defaultInstance;
    public static Scored getDefaultInstance() {
      return defaultInstance;
    }

    public Scored getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Scored(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              score_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.internal_static_com_kerpow_games_freethrow_common_Scored_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.internal_static_com_kerpow_games_freethrow_common_Scored_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.Scored.class, com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.Scored.Builder.class);
    }

    public static com.google.protobuf.Parser<Scored> PARSER =
        new com.google.protobuf.AbstractParser<Scored>() {
      public Scored parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Scored(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Scored> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int SCORE_FIELD_NUMBER = 2;
    private int score_;
    /**
     * <code>required int32 score = 2;</code>
     */
    public boolean hasScore() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 score = 2;</code>
     */
    public int getScore() {
      return score_;
    }

    private void initFields() {
      id_ = 0;
      score_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasScore()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, score_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, score_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.Scored parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.Scored parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.Scored parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.Scored parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.Scored parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.Scored parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.Scored parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.Scored parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.Scored parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.Scored parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.Scored prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.kerpow.games.freethrow.common.Scored}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.kerpow.games.freethrow.common.Scored)
        com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.ScoredOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.internal_static_com_kerpow_games_freethrow_common_Scored_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.internal_static_com_kerpow_games_freethrow_common_Scored_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.Scored.class, com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.Scored.Builder.class);
      }

      // Construct using com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.Scored.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        score_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.internal_static_com_kerpow_games_freethrow_common_Scored_descriptor;
      }

      public com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.Scored getDefaultInstanceForType() {
        return com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.Scored.getDefaultInstance();
      }

      public com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.Scored build() {
        com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.Scored result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.Scored buildPartial() {
        com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.Scored result = new com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.Scored(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.score_ = score_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.Scored) {
          return mergeFrom((com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.Scored)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.Scored other) {
        if (other == com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.Scored.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasScore()) {
          setScore(other.getScore());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasScore()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.Scored parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kerpow.games.freethrow.common.message.messages.ScoredOuterClass.Scored) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int score_ ;
      /**
       * <code>required int32 score = 2;</code>
       */
      public boolean hasScore() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 score = 2;</code>
       */
      public int getScore() {
        return score_;
      }
      /**
       * <code>required int32 score = 2;</code>
       */
      public Builder setScore(int value) {
        bitField0_ |= 0x00000002;
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 score = 2;</code>
       */
      public Builder clearScore() {
        bitField0_ = (bitField0_ & ~0x00000002);
        score_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.kerpow.games.freethrow.common.Scored)
    }

    static {
      defaultInstance = new Scored(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.kerpow.games.freethrow.common.Scored)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kerpow_games_freethrow_common_Scored_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_kerpow_games_freethrow_common_Scored_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Scored.proto\022!com.kerpow.games.freethr" +
      "ow.common\"#\n\006Scored\022\n\n\002id\030\001 \002(\005\022\r\n\005score" +
      "\030\002 \002(\005B4\n2com.kerpow.games.freethrow.com" +
      "mon.message.messages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_kerpow_games_freethrow_common_Scored_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_kerpow_games_freethrow_common_Scored_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_kerpow_games_freethrow_common_Scored_descriptor,
        new java.lang.String[] { "Id", "Score", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
