// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Shot.proto

package com.kerpow.games.freethrow.common.message;

public final class ShotOuterClass {
  private ShotOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ShotOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.kerpow.games.freethrow.common.Shot)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 time = 1;</code>
     */
    boolean hasTime();
    /**
     * <code>required int32 time = 1;</code>
     */
    int getTime();

    /**
     * <code>required int32 owner = 2;</code>
     */
    boolean hasOwner();
    /**
     * <code>required int32 owner = 2;</code>
     */
    int getOwner();
  }
  /**
   * Protobuf type {@code com.kerpow.games.freethrow.common.Shot}
   */
  public static final class Shot extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.kerpow.games.freethrow.common.Shot)
      ShotOrBuilder {
    // Use Shot.newBuilder() to construct.
    private Shot(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Shot(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Shot defaultInstance;
    public static Shot getDefaultInstance() {
      return defaultInstance;
    }

    public Shot getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Shot(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              time_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              owner_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kerpow.games.freethrow.common.message.ShotOuterClass.internal_static_com_kerpow_games_freethrow_common_Shot_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kerpow.games.freethrow.common.message.ShotOuterClass.internal_static_com_kerpow_games_freethrow_common_Shot_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kerpow.games.freethrow.common.message.ShotOuterClass.Shot.class, com.kerpow.games.freethrow.common.message.ShotOuterClass.Shot.Builder.class);
    }

    public static com.google.protobuf.Parser<Shot> PARSER =
        new com.google.protobuf.AbstractParser<Shot>() {
      public Shot parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Shot(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Shot> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TIME_FIELD_NUMBER = 1;
    private int time_;
    /**
     * <code>required int32 time = 1;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 time = 1;</code>
     */
    public int getTime() {
      return time_;
    }

    public static final int OWNER_FIELD_NUMBER = 2;
    private int owner_;
    /**
     * <code>required int32 owner = 2;</code>
     */
    public boolean hasOwner() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 owner = 2;</code>
     */
    public int getOwner() {
      return owner_;
    }

    private void initFields() {
      time_ = 0;
      owner_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOwner()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, time_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, owner_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, time_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, owner_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.kerpow.games.freethrow.common.message.ShotOuterClass.Shot parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kerpow.games.freethrow.common.message.ShotOuterClass.Shot parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kerpow.games.freethrow.common.message.ShotOuterClass.Shot parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kerpow.games.freethrow.common.message.ShotOuterClass.Shot parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kerpow.games.freethrow.common.message.ShotOuterClass.Shot parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kerpow.games.freethrow.common.message.ShotOuterClass.Shot parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.kerpow.games.freethrow.common.message.ShotOuterClass.Shot parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.kerpow.games.freethrow.common.message.ShotOuterClass.Shot parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.kerpow.games.freethrow.common.message.ShotOuterClass.Shot parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kerpow.games.freethrow.common.message.ShotOuterClass.Shot parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.kerpow.games.freethrow.common.message.ShotOuterClass.Shot prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.kerpow.games.freethrow.common.Shot}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.kerpow.games.freethrow.common.Shot)
        com.kerpow.games.freethrow.common.message.ShotOuterClass.ShotOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kerpow.games.freethrow.common.message.ShotOuterClass.internal_static_com_kerpow_games_freethrow_common_Shot_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kerpow.games.freethrow.common.message.ShotOuterClass.internal_static_com_kerpow_games_freethrow_common_Shot_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kerpow.games.freethrow.common.message.ShotOuterClass.Shot.class, com.kerpow.games.freethrow.common.message.ShotOuterClass.Shot.Builder.class);
      }

      // Construct using com.kerpow.games.freethrow.common.message.ShotOuterClass.Shot.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        time_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        owner_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kerpow.games.freethrow.common.message.ShotOuterClass.internal_static_com_kerpow_games_freethrow_common_Shot_descriptor;
      }

      public com.kerpow.games.freethrow.common.message.ShotOuterClass.Shot getDefaultInstanceForType() {
        return com.kerpow.games.freethrow.common.message.ShotOuterClass.Shot.getDefaultInstance();
      }

      public com.kerpow.games.freethrow.common.message.ShotOuterClass.Shot build() {
        com.kerpow.games.freethrow.common.message.ShotOuterClass.Shot result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kerpow.games.freethrow.common.message.ShotOuterClass.Shot buildPartial() {
        com.kerpow.games.freethrow.common.message.ShotOuterClass.Shot result = new com.kerpow.games.freethrow.common.message.ShotOuterClass.Shot(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.owner_ = owner_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kerpow.games.freethrow.common.message.ShotOuterClass.Shot) {
          return mergeFrom((com.kerpow.games.freethrow.common.message.ShotOuterClass.Shot)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kerpow.games.freethrow.common.message.ShotOuterClass.Shot other) {
        if (other == com.kerpow.games.freethrow.common.message.ShotOuterClass.Shot.getDefaultInstance()) return this;
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasOwner()) {
          setOwner(other.getOwner());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTime()) {
          
          return false;
        }
        if (!hasOwner()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kerpow.games.freethrow.common.message.ShotOuterClass.Shot parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kerpow.games.freethrow.common.message.ShotOuterClass.Shot) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int time_ ;
      /**
       * <code>required int32 time = 1;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 time = 1;</code>
       */
      public int getTime() {
        return time_;
      }
      /**
       * <code>required int32 time = 1;</code>
       */
      public Builder setTime(int value) {
        bitField0_ |= 0x00000001;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 time = 1;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0;
        onChanged();
        return this;
      }

      private int owner_ ;
      /**
       * <code>required int32 owner = 2;</code>
       */
      public boolean hasOwner() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 owner = 2;</code>
       */
      public int getOwner() {
        return owner_;
      }
      /**
       * <code>required int32 owner = 2;</code>
       */
      public Builder setOwner(int value) {
        bitField0_ |= 0x00000002;
        owner_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 owner = 2;</code>
       */
      public Builder clearOwner() {
        bitField0_ = (bitField0_ & ~0x00000002);
        owner_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.kerpow.games.freethrow.common.Shot)
    }

    static {
      defaultInstance = new Shot(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.kerpow.games.freethrow.common.Shot)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kerpow_games_freethrow_common_Shot_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_kerpow_games_freethrow_common_Shot_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nShot.proto\022!com.kerpow.games.freethrow" +
      ".common\"#\n\004Shot\022\014\n\004time\030\001 \002(\005\022\r\n\005owner\030\002" +
      " \002(\005B+\n)com.kerpow.games.freethrow.commo" +
      "n.message"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_kerpow_games_freethrow_common_Shot_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_kerpow_games_freethrow_common_Shot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_kerpow_games_freethrow_common_Shot_descriptor,
        new java.lang.String[] { "Time", "Owner", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
